# Generated by Django 4.1.5 on 2023-02-12 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_height', models.IntegerField(editable=False, null=True)),
                ('image_width', models.IntegerField(editable=False, null=True)),
                ('thumb_height', models.IntegerField(editable=False, null=True)),
                ('thumb_width', models.IntegerField(editable=False, null=True)),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('group_variety', models.CharField(choices=[('open', 'Открытая'), ('closed', 'Закрытая'), ('private', 'Приватная'), ('team', 'Команда')], default='open', max_length=10, verbose_name='Вид группы')),
                ('desc', models.TextField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(height_field='image_height', upload_to='groups/image/', verbose_name='Изображение', width_field='image_width')),
                ('miniature', models.ImageField(height_field='thumb_height', upload_to='groups/miniature/', verbose_name='Миниатюра', width_field='thumb_width')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Основатель')),
                ('members', models.ManyToManyField(blank=True, related_name='partner', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Группа и команда',
                'verbose_name_plural': 'Группы и команды',
            },
        ),
        migrations.CreateModel(
            name='GroupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('link', models.URLField(verbose_name='URL')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.groups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Ссылка группы',
                'verbose_name_plural': 'Ссылки группы',
            },
        ),
        migrations.CreateModel(
            name='EntryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Заголовок записи')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст записи')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='community.groups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Запись группы',
                'verbose_name_plural': 'Записи группы',
            },
        ),
        migrations.CreateModel(
            name='CommentEntryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Сообщение')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален?')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='community.entrygroup', verbose_name='Запись')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='community.commententrygroup', verbose_name='Родительский комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'abstract': False,
            },
        ),
    ]
