# Generated by Django 4.1.5 on 2023-02-11 11:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mini_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=5000, verbose_name='Краткое содержание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=10000000, verbose_name='Полное содержание'),
        ),
    ]
